name: Run Python Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance selenium python-dotenv robin_stocks firebase-admin pyotp

      - name: Set up Chrome for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          sudo apt-get install -y xvfb
          
          # Download and set up chromedriver
          LATEST_RELEASE=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/${LATEST_RELEASE}/chromedriver_linux64.zip
          unzip -o chromedriver_linux64.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver_linux64.zip

      - name: Run Python Script
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          ROBIN_MFA: ${{ secrets.ROBIN_MFA }}
          ROBIN_USERNAME: ${{ secrets.ROBIN_USERNAME }}
          ROBIN_PASSWORD: ${{ secrets.ROBIN_PASSWORD }}
        run: |
          # Run script with Xvfb to simulate a display environment for headless Chrome
          xvfb-run -a python YahooOptions.py
