name: Run Python Script

on:
  push:
    branches:
      - main
          
  # Runs at 6:20 AM PST, Monday through Friday
  schedule:
    - cron: '20 13 * * 1-5'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance selenium python-dotenv robin_stocks firebase-admin pyotp

      - name: Debug Chromedriver
        run: |
          # Ensure chromedriverGitHub is executable
          chmod +x ./chromedriverGitHub
          ls -l ./chromedriverGitHub

          # Move it to /usr/local/bin and ensure it's the correct one
          sudo mv ./chromedriverGitHub /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

          # Double-check the file type and permissions after moving
          file /usr/local/bin/chromedriver
          ls -l /usr/local/bin/chromedriver

      - name: Run Python Script
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          ROBIN_MFA: ${{ secrets.ROBIN_MFA }}
          ROBIN_USERNAME: ${{ secrets.ROBIN_USERNAME }}
          ROBIN_PASSWORD: ${{ secrets.ROBIN_PASSWORD }}
        run: |
          xvfb-run -a python YahooOptions.py
