name: Run Python Script with Pinned Chrome and ChromeDriver

on:
  schedule:
    - cron: '10 14 * * 1-5'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance selenium python-dotenv robin_stocks firebase-admin pyotp

      - name: Download and Set Up Chrome
        run: |
          # Download Chrome 131.0.6778.69
          wget https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.69/linux64/chrome-linux64.zip
          # Unzip Chrome to /usr/local/bin/
          unzip chrome-linux64.zip -d /usr/local/bin/
          # Make Chrome executable
          sudo chmod +x /usr/local/bin/chrome-linux64/chrome
          # Verify Chrome version
          /usr/local/bin/chrome-linux64/chrome --version

      - name: Download and Set Up ChromeDriver
        run: |
          # Download ChromeDriver 131.0.6778.69
          wget https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.69/linux64/chromedriver-linux64.zip
          # Unzip ChromeDriver
          unzip chromedriver-linux64.zip -d /tmp/chromedriver/
          # Move the binary to /usr/local/bin/
          sudo mv /tmp/chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          # Make ChromeDriver executable
          sudo chmod +x /usr/local/bin/chromedriver
          # Verify ChromeDriver version
          /usr/local/bin/chromedriver --version

      - name: Run Python Script
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          ROBIN_MFA: ${{ secrets.ROBIN_MFA }}
          ROBIN_USERNAME: ${{ secrets.ROBIN_USERNAME }}
          ROBIN_PASSWORD: ${{ secrets.ROBIN_PASSWORD }}
        run: |
          xvfb-run -a python YahooOptions.py
