name: Run Python Script

on:
  # Runs at 6:10 AM PST, Monday through Friday
  schedule:
    - cron: '00 13 * * 1-5'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance selenium python-dotenv robin_stocks firebase-admin pyotp

      - name: Install Chrome Version 129
        run: |
          sudo apt-get remove google-chrome-stable -y
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_129.0.6668.69-1_amd64.deb
          sudo dpkg -i google-chrome-stable_129.0.6668.69-1_amd64.deb
          google-chrome --version

      - name: Use local ChromeDriver 129
        run: |
          sudo mv ./chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          # Confirm ChromeDriver setup
          /usr/local/bin/chromedriver --version

      - name: Run Python Script
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          ROBIN_MFA: ${{ secrets.ROBIN_MFA }}
          ROBIN_USERNAME: ${{ secrets.ROBIN_USERNAME }}
          ROBIN_PASSWORD: ${{ secrets.ROBIN_PASSWORD }}
        run: |
          xvfb-run -a python YahooOptions.py
